import os

"Rename this file to sg_connection.py and fill in the Script Details"


# use your shotgun server name (i.e. "https://studioName.shotgunstudio.com")
os.environ["SERVER_PATH"] = 'https://example.shotgunstudio.com' 

# use the name of the shotgun api script that will do the query (needs to be set up in Shotgun's admin area)
os.environ["SCRIPT_NAME"] = 'shotgun_dropper' 

# use the script key as generated by Shotgun when the above script was created in Shotgun's admin area
os.environ["SCRIPT_KEY"] = 'xyxyxyxyxyxyxyxyxy'       